-- Add new fields to report_settings table for advanced customization
ALTER TABLE report_settings
ADD COLUMN IF NOT EXISTS evaluator_name text,
ADD COLUMN IF NOT EXISTS institution_name text,
ADD COLUMN IF NOT EXISTS institution_address text,
ADD COLUMN IF NOT EXISTS institution_phone text,
ADD COLUMN IF NOT EXISTS institution_email text,
ADD COLUMN IF NOT EXISTS show_qr_code boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS qr_code_position text DEFAULT 'bottom-right',
ADD COLUMN IF NOT EXISTS signature_url text,
ADD COLUMN IF NOT EXISTS signature_text text,
ADD COLUMN IF NOT EXISTS show_signature boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS font_family text DEFAULT 'helvetica',
ADD COLUMN IF NOT EXISTS body_font_size numeric DEFAULT 11,
ADD COLUMN IF NOT EXISTS show_watermark boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS watermark_text text,
ADD COLUMN IF NOT EXISTS custom_field_1_label text,
ADD COLUMN IF NOT EXISTS custom_field_1_value text,
ADD COLUMN IF NOT EXISTS custom_field_2_label text,
ADD COLUMN IF NOT EXISTS custom_field_2_value text,
ADD COLUMN IF NOT EXISTS custom_field_3_label text,
ADD COLUMN IF NOT EXISTS custom_field_3_value text,
ADD COLUMN IF NOT EXISTS border_color text DEFAULT '#e5e7eb',
ADD COLUMN IF NOT EXISTS border_width numeric DEFAULT 0.5,
ADD COLUMN IF NOT EXISTS show_header_border boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS show_footer_border boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS page_margins jsonb DEFAULT '{"top": 20, "right": 20, "bottom": 20, "left": 20}'::jsonb;