// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tctypxdamgmqrlswmxqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjdHlweGRhbWdtcXJsc3dteHFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5ODM0MTQsImV4cCI6MjA3NjU1OTQxNH0.6IO_gCv6U3gvsv2JrjC5ISlZCogQnX0WLhT8yWZoCDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});